using Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataAccess
{
    public class FlagContextInitializer : CreateDatabaseIfNotExists<FlagContext>
    {
        protected override void Seed(FlagContext context)
        {
            List<CountryFlag> seedFlags = new List<CountryFlag>
            {
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "AF", Description = "Afghanistan" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "AL", Description = "Albania" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "DZ", Description = "Algeria" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "AD", Description = "Andorra" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "AO", Description = "Angola" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "AG", Description = "Antigua and Barbuda" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "AR", Description = "Argentina" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "AM", Description = "Armenia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "AU", Description = "Australia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "AT", Description = "Austria" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "AZ", Description = "Azerbaijan" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "BS", Description = "Bahamas" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "BH", Description = "Bahrain" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "BD", Description = "Bangladesh" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "BB", Description = "Barbados" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "BY", Description = "Belarus" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "BE", Description = "Belgium" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "BZ", Description = "Belize" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "BJ", Description = "Benin" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "BT", Description = "Bhutan" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "BO", Description = "Bolivia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "BA", Description = "Bosnia and Herzegovina" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "BW", Description = "Botswana" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "BR", Description = "Brazil" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "BN", Description = "Brunei" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "BG", Description = "Bulgaria" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "BF", Description = "Burkina Faso" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "BI", Description = "Burundi" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "KH", Description = "Cambodia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "CM", Description = "Cameroon" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "CA", Description = "Canada" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "CV", Description = "Cape Verde" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "CF", Description = "Central African Republic" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "TD", Description = "Chad" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "CL", Description = "Chile" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "CO", Description = "Colombia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "KM", Description = "Comoros" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "CK", Description = "the Cook Islands" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "CR", Description = "Costa Rica" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "CI", Description = "Cote d'Ivoire" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "HR", Description = "Croatia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "CU", Description = "Cuba" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "CY", Description = "Cyprus" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "CZ", Description = "Czech Republic" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "CD", Description = "Democratic Republic of the Congo" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "DK", Description = "Denmark" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "DJ", Description = "Djibouti" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "DM", Description = "Dominica" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "DO", Description = "Dominican Republic" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "TL", Description = "East Timor" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "EC", Description = "Ecuador" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "EG", Description = "Egypt" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "SV", Description = "El Salvador" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "GQ", Description = "Equatorial Guinea" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "ER", Description = "Eritrea" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "EE", Description = "Estonia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "ET", Description = "Ethiopia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "FJ", Description = "Fiji" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "FI", Description = "Finland" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "FR", Description = "France" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "GA", Description = "Gabon" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "GM", Description = "Gambia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "GE", Description = "Georgia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "DE", Description = "Germany" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "GH", Description = "Ghana" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "GR", Description = "Greece" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "GD", Description = "Grenada" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "GT", Description = "Guatemala" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "GN", Description = "Guinea" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "GW", Description = "Guinea-Bissau" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "GY", Description = "Guyana" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "HT", Description = "Haiti" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "HN", Description = "Honduras" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "HU", Description = "Hungary" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "IS", Description = "Iceland" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "IN", Description = "India" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "ID", Description = "Indonesia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "IR", Description = "Iran" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "IQ", Description = "Iraq" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "IE", Description = "Ireland" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "IL", Description = "Israel" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "IT", Description = "Italy" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "JM", Description = "Jamaica" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "JP", Description = "Japan" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "JO", Description = "Jordan" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "KZ", Description = "Kazakhstan" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "KE", Description = "Kenya" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "KI", Description = "Kiribati" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "KS", Description = "Kosovo" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "KW", Description = "Kuwait" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "KG", Description = "Kyrgyzstan" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "LA", Description = "Laos" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "LV", Description = "Latvia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "LB", Description = "Lebanon" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "LS", Description = "Lesotho" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "LR", Description = "Liberia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "LY", Description = "Libya" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "LI", Description = "Liechtenstein" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "LT", Description = "Lithuania" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "LU", Description = "Luxembourg" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "MK", Description = "Macedonia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "MG", Description = "Madagascar" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "MW", Description = "Malawi" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "MY", Description = "Malaysia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "MV", Description = "Maldives" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "ML", Description = "Mali" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "MT", Description = "Malta" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "MH", Description = "Marshall Islands" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "MR", Description = "Mauritania" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "MU", Description = "Mauritius" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "MX", Description = "Mexico" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "FM", Description = "Micronesia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "MD", Description = "Moldova" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "MC", Description = "Monaco" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "MN", Description = "Mongolia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "ME", Description = "Montenegro" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "MA", Description = "Morocco" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "MZ", Description = "Mozambique" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "MM", Description = "Myanmar" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "NA", Description = "Namibia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "NR", Description = "Nauru" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "NP", Description = "Nepal" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "NL", Description = "Netherlands" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "NZ", Description = "New Zealand" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "NI", Description = "Nicaragua" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "NE", Description = "Niger" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "NG", Description = "Nigeria" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "NU", Description = "Niue" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "KP", Description = "North Korea" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "NO", Description = "Norway" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "OM", Description = "Oman" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "PK", Description = "Pakistan" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "PW", Description = "Palau" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "PA", Description = "Panama" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "PG", Description = "Papua New Guinea" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "PY", Description = "Paraguay" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "CN", Description = "People's Republic of China" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "PE", Description = "Peru" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "PH", Description = "Philippines" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "PL", Description = "Poland" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "PT", Description = "Portugal" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "QA", Description = "Qatar" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "TW", Description = "Republic of China" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "CG", Description = "Republic of the Congo" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "RO", Description = "Romania" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "RU", Description = "Russia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "RW", Description = "Rwanda" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "KN", Description = "Saint Kitts and Nevis" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "LC", Description = "Saint Lucia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "VC", Description = "Saint Vincent and the Grenadines" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "WS", Description = "Samoa" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "SM", Description = "San Marino" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "ST", Description = "Sao Tome and Principe" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "SA", Description = "Saudi Arabia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "SN", Description = "Senegal" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "RS", Description = "Serbia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "SC", Description = "Seychelles" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "SL", Description = "Sierra Leone" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "SG", Description = "Singapore" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "SK", Description = "Slovakia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "SI", Description = "Slovenia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "SB", Description = "Solomon Islands" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "SO", Description = "Somalia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "ZA", Description = "South Africa" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "KR", Description = "South Korea" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "SS", Description = "South Sudan" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "ES", Description = "Spain" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "LK", Description = "Sri Lanka" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "SD", Description = "Sudan" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "SR", Description = "Suriname" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "SZ", Description = "Swaziland" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "SE", Description = "Sweden" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "CH", Description = "Switzerland" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "SY", Description = "Syria" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "TJ", Description = "Tajikistan" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "TZ", Description = "Tanzania" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "TH", Description = "Thailand" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "TG", Description = "Togo" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "TO", Description = "Tonga" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "TT", Description = "Trinidad and Tobago" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "TN", Description = "Tunisia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "TR", Description = "Turkey" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "TM", Description = "Turkmenistan" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "TV", Description = "Tuvalu" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "UG", Description = "Uganda" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "UA", Description = "Ukraine" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "AE", Description = "United Arab Emirates" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "GB", Description = "United Kingdom" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "US", Description = "United States" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "UY", Description = "Uruguay" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "UZ", Description = "Uzbekistan" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "VU", Description = "Vanuatu" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "VA", Description = "Vatican City" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "VE", Description = "Venezuela" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "VN", Description = "Vietnam" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "EH", Description = "Western Sahara" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "YE", Description = "Yemen" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "ZM", Description = "Zambia" },
                new CountryFlag { ID = Guid.NewGuid(), CountryCode = "ZW", Description = "Zimbabwe" }

            };

            //seedFlags.Sort((x, y) => x.Description.CompareTo(y.Description)); //Not needed because SaveChanges() inserts in a random order
            seedFlags.ForEach(v => context.CountryFlag.Add(v));
            context.SaveChanges();

        }
    }
}
